[package]
name = "nswrap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1"
derive_builder = "0.12"
nix = "0.26"
xdg = "^2.1"
thiserror = "1.0"